In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import seaborn as sns
import torch
import ipdb

In [3]:
scaler = torch.tensor(0)

In [4]:
scaler.shape

torch.Size([])

In [5]:
vector = torch.tensor([0,1])
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
MATRIX = torch.tensor([[0,1],[2,3]])
MATRIX.ndim

2

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
TENSOR = torch.rand(3,3,3)

In [10]:
TENSOR

tensor([[[0.5727, 0.4159, 0.1507],
         [0.0926, 0.8460, 0.0524],
         [0.9779, 0.5449, 0.5045]],

        [[0.9508, 0.5077, 0.9568],
         [0.0026, 0.9637, 0.1984],
         [0.7816, 0.2220, 0.8235]],

        [[0.6660, 0.3164, 0.3295],
         [0.3164, 0.9443, 0.2946],
         [0.9671, 0.8412, 0.0212]]])

In [11]:
TENSOR_10_10_ZERO = torch.zeros(10,10)

In [12]:
TENSOR

tensor([[[0.5727, 0.4159, 0.1507],
         [0.0926, 0.8460, 0.0524],
         [0.9779, 0.5449, 0.5045]],

        [[0.9508, 0.5077, 0.9568],
         [0.0026, 0.9637, 0.1984],
         [0.7816, 0.2220, 0.8235]],

        [[0.6660, 0.3164, 0.3295],
         [0.3164, 0.9443, 0.2946],
         [0.9671, 0.8412, 0.0212]]])

In [13]:
A_RANGE = torch.arange(start = 0, end = 10, step = 1)
A_RANGE

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
copy_A_RANGE_zeros = torch.zeros_like(A_RANGE)
copy_A_RANGE_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
cuda0 = torch.device('cuda:0')

float_32_tensor = torch.tensor([2., 3., 5.],
                                dtype = torch.float32,
                                device= cuda0,
                               requires_grad = True)

RuntimeError: No CUDA GPUs are available

In [17]:
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

NameError: name 'float_32_tensor' is not defined

In [18]:
print(torch.cuda.is_available())

False


In [19]:
tensor = torch.tensor([1,2,3])

In [20]:
tensor + 10

tensor([11, 12, 13])

In [21]:
tensor * 10

tensor([10, 20, 30])

In [22]:
tensor - 10

tensor([-9, -8, -7])

In [23]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [24]:
tensor += 10
tensor

tensor([1, 2, 3])

In [25]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [26]:
tensor * tensor

tensor([1, 4, 9])

In [27]:
tensor.matmul(tensor) # same as 
torch.matmul(tensor, tensor) # # same as 
tensor @ tensor

tensor(14)

In [28]:
p = np.array([1.2,2.2,3.2])

In [29]:
tensor_p = torch.from_numpy(p)

In [30]:
tensor_p

tensor([1.2000, 2.2000, 3.2000], dtype=torch.float64)

In [31]:
tensor_p = tensor_p.to(torch.float32)

In [32]:
tensor_p.dtype

torch.float32

In [33]:
TENSOR = torch.rand(2,3)
TENSOR

tensor([[0.4629, 0.9817, 0.5260],
        [0.3161, 0.8827, 0.7309]])

In [34]:
TENSOR.T

tensor([[0.4629, 0.3161],
        [0.9817, 0.8827],
        [0.5260, 0.7309]])

In [3]:
TENSOR_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

TENSOR_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [5]:
torch.mm(TENSOR_A, TENSOR_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [17]:
x = torch.arange(0,100,10)

In [18]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
x.min()

tensor(0)

In [20]:
x.max()

tensor(90)

In [21]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [22]:
x.to(torch.float32).mean()

tensor(45.)

In [15]:
x.sum()

tensor(450.)

In [24]:
x.argmin()

tensor(0)

In [25]:
x.argmax()

tensor(9)

In [33]:
x = torch.arange(1, 10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x_reshaped = x.reshape(9)

In [41]:
x_reshaped

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
p = torch.tensor([1])
p.shape

torch.Size([1])

In [37]:
p = p.reshape(0)
p.shape

RuntimeError: shape '[0]' is invalid for input of size 1

In [46]:
z = x.view(1, 9)

In [48]:
z[ : , 0] = 5

In [51]:
x[0]

tensor(5)

In [50]:
z

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [56]:
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [57]:
non_squeezed_tensor = torch.rand(2,1,3,2,1,2)

squeezed_tensor = torch.squeeze(non_squeezed_tensor)

In [58]:
non_squeezed_tensor.shape, squeezed_tensor.shape

(torch.Size([2, 1, 3, 2, 1, 2]), torch.Size([2, 3, 2, 2]))

In [63]:
a = torch.arange(1,10)
a, a.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [68]:
a_unsqueezed = a.unsqueeze(1)
a_unsqueezed, a_unsqueezed.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [72]:
# torch.premute - rearranges dimension of a tensor
a = torch.rand(224, 224, 3) # [height, width, color]

a_redim = torch.permute(a, (2, 0, 1)) # [color, height, width]

In [73]:
a_redim.shape

torch.Size([3, 224, 224])

In [76]:
array = np.arange(1., 8.)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [80]:
tensor = torch.from_numpy(array)
tensor.to(torch.float32)

tensor([1., 2., 3., 4., 5., 6., 7.])

In [84]:
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'

In [85]:
# tensor on GPU

tensor_on_gpu = tensor.to(device)

In [86]:
tensor.device

device(type='cpu')