In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import seaborn as sns
import torch
import ipdb

In [3]:
scaler = torch.tensor(0)

In [4]:
scaler.shape

torch.Size([])

In [5]:
vector = torch.tensor([0,1])
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
MATRIX = torch.tensor([[0,1],[2,3]])
MATRIX.ndim

2

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
TENSOR = torch.rand(3,3,3)

In [10]:
TENSOR

tensor([[[0.5727, 0.4159, 0.1507],
         [0.0926, 0.8460, 0.0524],
         [0.9779, 0.5449, 0.5045]],

        [[0.9508, 0.5077, 0.9568],
         [0.0026, 0.9637, 0.1984],
         [0.7816, 0.2220, 0.8235]],

        [[0.6660, 0.3164, 0.3295],
         [0.3164, 0.9443, 0.2946],
         [0.9671, 0.8412, 0.0212]]])

In [11]:
TENSOR_10_10_ZERO = torch.zeros(10,10)

In [12]:
TENSOR

tensor([[[0.5727, 0.4159, 0.1507],
         [0.0926, 0.8460, 0.0524],
         [0.9779, 0.5449, 0.5045]],

        [[0.9508, 0.5077, 0.9568],
         [0.0026, 0.9637, 0.1984],
         [0.7816, 0.2220, 0.8235]],

        [[0.6660, 0.3164, 0.3295],
         [0.3164, 0.9443, 0.2946],
         [0.9671, 0.8412, 0.0212]]])

In [13]:
A_RANGE = torch.arange(start = 0, end = 10, step = 1)
A_RANGE

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
copy_A_RANGE_zeros = torch.zeros_like(A_RANGE)
copy_A_RANGE_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
cuda0 = torch.device('cuda:0')

float_32_tensor = torch.tensor([2., 3., 5.],
                                dtype = torch.float32,
                                device= cuda0,
                               requires_grad = True)

RuntimeError: No CUDA GPUs are available

In [17]:
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

NameError: name 'float_32_tensor' is not defined

In [18]:
print(torch.cuda.is_available())

False


In [19]:
tensor = torch.tensor([1,2,3])

In [20]:
tensor + 10

tensor([11, 12, 13])

In [21]:
tensor * 10

tensor([10, 20, 30])

In [22]:
tensor - 10

tensor([-9, -8, -7])

In [23]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [24]:
tensor += 10
tensor

tensor([1, 2, 3])

In [25]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [26]:
tensor * tensor

tensor([1, 4, 9])

In [27]:
tensor.matmul(tensor) # same as 
torch.matmul(tensor, tensor) # # same as 
tensor @ tensor

tensor(14)

In [28]:
p = np.array([1.2,2.2,3.2])

In [29]:
tensor_p = torch.from_numpy(p)

In [30]:
tensor_p

tensor([1.2000, 2.2000, 3.2000], dtype=torch.float64)

In [31]:
tensor_p = tensor_p.to(torch.float32)

In [32]:
tensor_p.dtype

torch.float32

In [33]:
TENSOR = torch.rand(2,3)
TENSOR

tensor([[0.4629, 0.9817, 0.5260],
        [0.3161, 0.8827, 0.7309]])

In [34]:
TENSOR.T

tensor([[0.4629, 0.3161],
        [0.9817, 0.8827],
        [0.5260, 0.7309]])

In [16]:
torch. 

SyntaxError: invalid syntax (2964566908.py, line 1)