In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
home_price_data = pd.read_csv('../datasets/homeprices_2.csv')

In [7]:
home_price_data.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [8]:
home_price_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   town    13 non-null     object
 1   area    13 non-null     int64 
 2   price   13 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 444.0+ bytes


In [13]:
dummies = pd.get_dummies(home_price_data.town)

home_data_with_dummies = pd.concat([home_price_data, dummies], axis= 'columns')

cleaned_data = home_data_with_dummies.drop(['town', 'west windsor'], axis='columns')

home_data_with_dummies.head()
cleaned_data.head()

area   price  monroe township  robinsville
0  2600  550000             True        False
1  3000  565000             True        False
2  3200  610000             True        False
3  3600  680000             True        False
4  4000  725000             True        False

In [15]:
X = cleaned_data.drop(['price'], axis='columns')
y = cleaned_data.price

In [18]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X,y)

model.predict([[2800,0,1]])

c:\Users\yarra\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [21]:
model.score(X,y)

# saving the model 
import joblib

joblib.dump(model, 'home_prices_catogircal_values')

# to load the model 
# model = joblib.load('home_prices_catogircal_values')


['home_prices_catogircal_values']

In [33]:
# using preprocessing
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

home_data_encoded = le.fit_transform(home_price_data.town)
home_data_encoded
encoded_data = home_price_data

# direclty assign it to town
encoded_data.town = le.fit_transform(encoded_data.town)
encoded_data

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [49]:
X = encoded_data[['town', 'area']].values
y = encoded_data.price.values
X
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000])

In [50]:
 # one hot encoder - create dummies
 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')

X = ct.fit_transform(X)
X

X = X[:,1:] # dropping 1 colums
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [51]:
model.fit(X,y)
model.predict([[0,1,3400]]) 

array([681241.6684584])